# Stupidity Rocks Hugo theme
# Configuration parameters.

theme = "stupidity_rocks"
title = "Page Title"

disableKinds = ["page", "RSS", "section", "taxonomy", "term"]

[author]
  name = "Site Author"

[params]
  bannerTitle = "Banner Title"
  bannerMessage = "Banner message."
  copyright = "Copyright message"
  description = "Website description"
  madein = "'Made in' message"
  ribbonText = "Ribbon Text"

[params.colors]
  background = "#293f50"
  font = "#f1f3f4"
  ribbonBackground = "#1a1b1f"
  ribbonFont = "#f1f3f4"
