# Stupidity Rocks Hugo theme
# Configuration parameters.

copyright = "Copyright message"
theme = "stupidity_rocks"
title = "Page Title"

[author]
  name = "Site Author"

[params]
  headerTitle = "Banner Title"
  headerSubtitle = "Banner message."
  description = "Website description"
  madein = "'Made in' message"
  ribbonText = "Ribbon Text"

  [params.style]
    backgroundColor = "#293f50"
    backgroundColorRibbon = "#1a1b1f"
    fontColor = "#f1f3f4"
    fontColorHover = "#f1f3f4"
    fontColorRibbon = "#f1f3f4"

[module]
  [module.hugoVersion]
    min = "0.74.0"
    extended = true
