# stupidity_rocks theme metadata

name = "stupidity_rocks"
license = "MIT"
licenselink = "https://github.com/fscm/hugo-stupidity_rocks/blob/master/LICENSE"
description = "stupidity.rocks website theme"
homepage = "https://github.com/fscm/hugo-stupidity_rocks/"
tags = ["minimal", "responsive", "simple", "single page", "landing page"]
features = []
min_version = "0.74.0"

[author]
  name = "Frederico Martins"
  homepage = "http://stupidity.rocks/"
